web/common/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.views import login, logout

accounts = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
]

urlpatterns = [
    url(r'^accounts/', include(accounts, namespace='accounts')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),
]

web/sitt/urls.py
from django.conf.urls import include, url


urlpatterns = [
    url(r'^', include('common.urls')),
    url(r'^', include('tracker.urls', namespace='tracker')),
]

web/tracker/urls.py
from django.conf.urls import url, include

from . import views


events = [
    url(r'^$', views.EventListView.as_view(), name='index'),
    url(r'^create/$', views.EventCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', views.EventView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/update/$',
        views.EventUpdateView.as_view(),
        name='update'),
]

entries = [
    url(r'^$', views.EntryListView.as_view(), name='index'),
    url(r'^create/$', views.EntryCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', views.EntryView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/close/$', views.EntryCloseView.as_view(), name='close'),
    url(r'^(?P<pk>\d+)/update/$',
        views.EntryUpdateView.as_view(),
        name='update'),
]

tags = [
    url(r'^$', views.TagListView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.TagView.as_view(), name='detail'),
]

urlpatterns = [
    url(r'^events/', include(events, namespace='events')),
    url(r'^entries/', include(entries, namespace='entries')),
    url(r'^tags/', include(tags, namespace='tags')),
    url(r'^stats/$', views.StatsView.as_view(), name='stats'),
    url(r'^top/$', views.TopView.as_view(), name='top'),
    url(r'^$', views.MainView.as_view(), name='main'),
]

web/common/views.py
from django.views.decorators.http import require_GET, require_POST
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator


class SiteMixin:
    section = None
    sidebar = False

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['site_section'] = self.section
        context['site_sidebar'] = self.sidebar
        return context


def make_view_mixin(class_name, decorator):
    mixin = type(class_name, (object, ), {})

    def dispatch(self, *args, **kwargs):
        return super(mixin, self).dispatch(*args, **kwargs)

    mixin.dispatch = method_decorator(decorator)(dispatch)
    return mixin


GetMixin = make_view_mixin('GetMixin', require_GET)
LoginMixin = make_view_mixin('LoginMixin', login_required)
PostMixin = make_view_mixin('PostMixin', require_POST)


class AdminMixin(LoginMixin):

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_superuser:
            raise PermissionDenied
        return super().dispatch(self, request, *args, **kwargs)


class UserMixin(LoginMixin):

    def dispatch(self, request, *args, **kwargs):
        try:
            object = self.get_object()
        except AttributeError:
            raise Http404(
                "Could not check permissions because no model was found."
            )
        else:
            if request.user.is_superuser or request.user == object.user:
                return super().dispatch(self, request, *args, **kwargs)
            else:
                raise PermissionDenied

web/common/templates/base.html
{% load staticfiles %}
{% load bootstrap3 %}
<!doctype html>

<html lang="en">
<head>
    <meta charset="utf-8">
    <title>{% block html_title %}{% block section_title %}{% endblock %}{% endblock %}{{ site_name }}</title>
    <meta name="description" content="If it's here, you'll find it.">
    <meta name="author" content="Alkxzv">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% for link in css_includes %}
    <link type="text/css" rel="stylesheet" href="{% static link %}">
    {% endfor %}
    {% block head %}{% block section_head %}{% endblock %}{% endblock %}
</head>
<body>
    <header class="navbar navbar-inverse navbar-static-top" role="banner">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <entry class="sr-only">Toggle navigation</entry>
                    <entry class="icon-bar"></entry>
                    <entry class="icon-bar"></entry>
                    <entry class="icon-bar"></entry>
                </button>
                <a class="navbar-brand" href="{% url 'tracker:main' %}">{{ site_name }}</a>
            </div>
            <nav class="collapse navbar-collapse" role="navigation">
                <ul class="nav navbar-nav">
                    {% block navigation %}
                    {% block section_navigation %}{% endblock %}
                    {% if user.is_staff %}
                    <li><a href="/admin/">Admin</a></li>
                    {% endif %}
                    {% endblock navigation %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a>{{ user.username }}</a></li>
                    <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </header>
    <div class="container">
        <div class="row">
            {% if site_sidebar %}<div class="col-md-9 col-sm-8 main">{% else %}<div class="col-lg-12 col-md-12 col-sm-12 main">{% endif %}
                {% block content %}{% block section_content %}{% endblock %}{% endblock %}
            </div>
            {% if site_sidebar %}<div class="col-md-3 col-sm-4 sidebar">{% else %}<div class="hidden sidebar">{% endif %}
                {% block sidebar %}{% block section_sidebar %}{% endblock %}{% endblock %}
            </div>
        </div>
    </div>
    {% for link in js_includes %}
    <script src="{% static link %}"></script>
    {% endfor %}
    {% block foot %}{% block section_foot %}{% endblock %}{% endblock %}
</body>
</html>