web/sitt/urls.py
from django.conf.urls import include, url


urlpatterns = [
    url(r'^', include('common.urls')),
    url(r'^', include('tracker.urls', namespace='tracker')),
]

web/tracker/urls.py
from django.conf.urls import url, include

from . import views


events = [
    url(r'^$', views.EventListView.as_view(), name='index'),
    url(r'^create/$', views.EventCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', views.EventView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/update/$',
        views.EventUpdateView.as_view(),
        name='update'),
]

entries = [
    url(r'^$', views.EntryListView.as_view(), name='index'),
    url(r'^create/$', views.EntryCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', views.EntryView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/close/$', views.EntryCloseView.as_view(), name='close'),
    url(r'^(?P<pk>\d+)/update/$',
        views.EntryUpdateView.as_view(),
        name='update'),
]

tags = [
    url(r'^$', views.TagListView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.TagView.as_view(), name='detail'),
]

urlpatterns = [
    url(r'^events/', include(events, namespace='events')),
    url(r'^entries/', include(entries, namespace='entries')),
    url(r'^tags/', include(tags, namespace='tags')),
    url(r'^stats/$', views.StatsView.as_view(), name='stats'),
    url(r'^top/$', views.TopView.as_view(), name='top'),
    url(r'^$', views.MainView.as_view(), name='main'),
]

web/tracker/models.py
from collections import defaultdict
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
import datetime as dt

PRO = (
    (None, "~"),
    (1, "Finished"),
    (2, "Dropped"),
    (3, "Ongoing"),
    (4, "Waiting"),
)

RAT = (
    (None, "~"),
    (0, "○○○○○ Terrible"),
    (1, "●○○○○ Poor"),
    (2, "●●○○○ Okay"),
    (3, "●●●○○ Good"),
    (4, "●●●●○ Great"),
    (5, "●●●●● Excellent"),
)

START_DATE = dt.datetime(2010, 1, 1).replace(tzinfo=timezone.utc)


# Entries

class EntryQuerySet(models.query.QuerySet):

    def duration_over_time(self):
        datetime_sum = defaultdict(int)
        for datetime, duration in self.values_list('datetime', 'duration'):
            if duration and datetime >= START_DATE:
                datetime_sum[datetime.date()] += duration
        keys = datetime_sum.keys()
        if keys:
            d, end = min(keys), max(keys)
            while d <= end:
                datetime_sum[d] = datetime_sum.get(d, 0)
                d += dt.timedelta(days=1)
        return datetime_sum


class EntryManager(models.Manager):
    use_for_related_fields = True

    def get_queryset(self):
        return EntryQuerySet(self.model)


class Entry(models.Model):
    datetime = models.DateTimeField()
    event = models.ForeignKey('tracker.Event', related_name='entries')
    duration = models.SmallIntegerField(blank=True, null=True)
    annotation = models.TextField(blank=True)
    objects = EntryManager()

    class Meta:
        ordering = '-datetime',
        verbose_name_plural = "entries"

    def __str__(self):
        return '[{}] {}'.format(self.datetime, self.event.title)

    def get_absolute_url(self):
        return self.event.get_absolute_url()


# Events

class EventQuerySet(models.query.QuerySet):

    def annotate_duration(self):
        d = models.Sum('entries__duration')
        return self.annotate(duration=d)


class EventManager(models.Manager):
    use_for_related_fields = True

    def get_queryset(self):
        return EventQuerySet(self.model)


class Event(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=100, blank=True, null=True)
    date = models.DateField(blank=True, null=True)
    progress = models.SmallIntegerField(blank=True, null=True, choices=PRO)
    rating = models.SmallIntegerField(blank=True, null=True, choices=RAT)
    tags = models.ManyToManyField('tracker.Tag',
                                  blank=True,
                                  related_name='events')
    objects = EventManager()

    class Meta:
        unique_together = ('title', 'date'),
        ordering = '-date',

    def __str__(self):
        return '{} ({})'.format(self.title, self.date.year)

    def get_absolute_url(self):
        return reverse('tracker:events:detail', args=[self.pk])

    def get_duration(self):
        duration = self.entries.aggregate(sum=models.Sum('duration'))['sum']
        return 0 if duration is None else duration

    def entry_count(self):
        return self.entries.count()


# Tags

class TagQuerySet(models.query.QuerySet):

    def annotate_duration(self):
        d = models.Sum('events__entries__duration')
        return self.annotate(duration=d)

    def annotate_rating(self):
        r = models.Avg('events__rating')
        return self.annotate(rating=r)


class TagManager(models.Manager):
    use_for_related_fields = True

    def get_queryset(self):
        return TagQuerySet(self.model)


class Tag(models.Model):
    value = models.CharField(unique=True, max_length=50)
    objects = TagManager()

    class Meta:
        ordering = 'value',

    def __str__(self):
        return '[{}]'.format(self.value)

    def get_duration(self):
        aggregated = self.events.aggregate(sum=models.Sum('entries__duration'))
        duration = aggregated['sum']
        return 0 if duration is None else duration

    def get_rating(self):
        events = self.events.all().annotate(count=models.Count('entries'))
        total = sum(x.rating * x.count for x in events if x.rating)
        duration = sum(x.count for x in events if x.rating)
        return total / duration if duration > 0 else None

    def event_count(self):
        return self.events.count()

    def entry_count(self):
        events = self.events.all()
        return Entry.objects.filter(event__in=events).count()

    def get_absolute_url(self):
        return reverse('tracker:tags:detail', args=[self.pk])

web/tracker/forms.py
from django import forms

from . import models

HT = 'Write tags, separated by semicolon.'


class EventForm(forms.ModelForm):
    add_tags = forms.CharField(max_length=100, help_text=HT, required=False)
    remove_tags = forms.CharField(max_length=100, help_text=HT, required=False)

    class Meta:
        model = models.Event
        fields = 'title', 'description', 'date', 'progress', 'rating'

    def clean_add_tags(self):
        return [v.strip() for v in self.cleaned_data['add_tags'].split(';')]

    def clean_remove_tags(self):
        return [v.strip() for v in self.cleaned_data['remove_tags'].split(';')]

    def save(self, *args, **kwargs):
        event = super().save(*args, **kwargs)
        for value in self.cleaned_data['remove_tags']:
            try:
                tag = event.tags.get(value=value)
            except models.Tag.DoesNotExist:
                tag = None
            else:
                event.tags.remove(tag)
        for value in self.cleaned_data['add_tags']:
            if value:
                tag, created = models.Tag.objects.get_or_create(value=value)
                event.tags.add(tag)
        return event

web/tracker/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.views.generic import (CreateView, DetailView, ListView,
                                  TemplateView, UpdateView)
import datetime as dt
import json

from . import models, forms
from .nvd3 import (duration_chart_data, duration_weekday_chart_data,
                   duration_monthly_chart_data, duration_yearly_chart_data)
from common.views import LoginMixin, SiteMixin


class MainView(LoginMixin, SiteMixin, TemplateView):
    template_name = 'tracker/index.html'
    section = 'tracker'

    def get_context_data(self):
        context = super().get_context_data()
        events = models.Event.objects.filter(progress=3).annotate_duration()
        context['ongoing_events'] = events.order_by('-duration')
        events = models.Event.objects.filter(progress=4).annotate_duration()
        context['waiting_events'] = events.order_by('-duration')
        entries = models.Entry.objects.filter(duration=None)
        context['pending_entries'] = entries.order_by('-datetime')
        return context


class StatsView(LoginMixin, SiteMixin, TemplateView):
    template_name = 'tracker/stats.html'
    section = 'stats'

    def get_context_data(self):
        context = super().get_context_data()
        duration = models.Entry.objects.all().duration_over_time()
        duration_data = duration_weekday_chart_data(duration)
        context['weekday_data'] = json.dumps(duration_data)
        duration_data = duration_monthly_chart_data(duration)
        context['monthly_data'] = json.dumps(duration_data)
        duration_data = duration_yearly_chart_data(duration)
        context['yearly_data'] = json.dumps(duration_data)
        # This time n years ago
        context['n_years_ago'] = []
        today = dt.date.today()
        delta = dt.timedelta(3)
        for year in range(today.year - 1, 2007, -1):
            start = dt.datetime(year, today.month, today.day, 0, 0) - delta
            start = start.replace(tzinfo=timezone.utc)
            end = dt.datetime(year, today.month, today.day, 23, 59) + delta
            end = end.replace(tzinfo=timezone.utc)
            entries = models.Entry.objects.filter(datetime__range=(start, end))
            if entries:
                context['n_years_ago'].append((year, entries))
        return context


class TopView(SiteMixin, ListView):
    template_name = 'tracker/top.html'
    section = 'top'
    queryset = models.Event.objects.all()\
        .annotate_duration()\
        .order_by('-rating', '-duration')


# Entries

class EntryMixin(LoginMixin, SiteMixin):
    model = models.Entry
    section = 'entries'


class EntryView(EntryMixin, DetailView):
    pass


class EntryCreateView(EntryMixin, CreateView):
    fields = 'datetime', 'event', 'duration', 'annotation'

    def get_initial(self):
        try:
            event_pk = self.request.GET.get('event')
            event = models.Event.objects.get(id=event_pk)
            initial = {'event': event}
        except models.Event.DoesNotExist:
            initial = {}
        finally:
            initial['datetime'] = timezone.now()
        return initial


class EntryUpdateView(EntryMixin, UpdateView):
    fields = 'datetime', 'event', 'duration', 'annotation'


class EntryListView(EntryMixin, ListView):
    queryset = models.Entry.objects.all()\
        .select_related('event')\
        .order_by('-datetime')
    paginate_by = 100

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        object_list = context['object_list']
        if object_list is not None:
            duration = object_list.duration_over_time()
            duration_data = duration_chart_data(duration)
            context['duration_data'] = json.dumps(duration_data)
        return context


class EntryCloseView(EntryMixin, UpdateView):

    def dispatch(self, request, *args, **kwargs):
        instance = self.get_object()
        delta = timezone.now() - instance.datetime
        instance.duration = int(delta.days * 24 * 60 + delta.seconds / 60)
        instance.save()
        url = reverse('tracker:events:detail', args=[instance.event.id])
        return HttpResponseRedirect(url)


# Events

class EventMixin(LoginMixin, SiteMixin):
    model = models.Event
    section = 'events'


class EventView(EventMixin, DetailView):

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        entries = self.object.entries.all()
        context['entry_list'] = entries.order_by('-datetime')
        context['tag_list'] = self.object.tags.all().order_by('value')
        duration = entries.duration_over_time()
        context['duration_data'] = json.dumps(duration_chart_data(duration))
        return context


class EventCreateView(EventMixin, CreateView):
    form_class = forms.EventForm


class EventUpdateView(EventMixin, UpdateView):
    form_class = forms.EventForm


class EventListView(EventMixin, ListView):
    paginate_by = 100
    queryset = models.Event.objects.all()\
        .annotate_duration()\
        .order_by('-date')


# Tags

class TagMixin(LoginMixin, SiteMixin):
    model = models.Tag
    section = 'tags'


class TagView(TagMixin, DetailView):

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        events = self.object.events.exclude(rating=None).annotate_duration()
        context['event_list'] = events.order_by('-rating', '-duration')
        entries = models.Entry.objects.filter(event__in=events)
        entries = entries.select_related('event')
        context['entry_list'] = entries.order_by('-datetime')
        duration = entries.duration_over_time()
        duration_data = duration_monthly_chart_data(duration)
        context['duration_data'] = json.dumps(duration_data)
        return context


class TagListView(TagMixin, ListView):
    queryset = models.Tag.objects.all()\
        .annotate_duration()\
        .annotate_rating()\
        .extra(select={'upper': 'upper(value)'})\
        .order_by('upper')
    paginate_by = 100

web/tracker/templates/tracker/base.html
{% extends 'base.html' %}

{% block section_navigation %}
    {% if user.is_authenticated %}
    <li{% if site_section == 'tracker' %} class="active" {% endif %}>
        <a href="{% url 'tracker:main' %}">Tracker</a>
    </li>
    <li{% if site_section == 'entries' %} class="active" {% endif %}>
        <a href="{% url 'tracker:entries:index' %}">Entries</a>
    </li>
    <li{% if site_section == 'events' %} class="active" {% endif %}>
        <a href="{% url 'tracker:events:index' %}">Events</a>
    </li>
    <li{% if site_section == 'tags' %} class="active" {% endif %}>
        <a href="{% url 'tracker:tags:index' %}">Tags</a>
    </li>
    <li{% if site_section == 'stats' %} class="active" {% endif %}>
        <a href="{% url 'tracker:stats' %}">Stats</a>
    </li>
    {% endif %}
    <li{% if site_section == 'top' %} class="active" {% endif %}>
        <a href="{% url 'tracker:top' %}">Top</a>
    </li>
{% endblock section_navigation %}

web/tracker/templates/tracker/entry_form.html
{% extends 'tracker/base.html' %}
{% load bootstrap3 %}
{% load tracker %}

{% block section_title %}Edit - {% endblock %}

{% block section_content %}
<h2>Edit entry</h2>
<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="form-group text-right">
        {% if entry and not entry.duration %}
        <a class="btn btn-default" href="{% url 'tracker:entries:close' entry.pk %}">Close Now</a>
        {% endif %}
        <input type="submit" class="btn btn-default" value="Save"/>
    </div>
</form>
{% endblock section_content %}

web/tracker/templates/tracker/entry_list.html
{% extends 'tracker/base.html' %}
{% load bootstrap3 %}

{% block section_title %}Entries - {% endblock %}

{% block section_content %}
<h2>Entries</h2>
<div class="title-icon"><a href="{% url 'tracker:entries:create' %}"><entry class="glyphicon glyphicon-plus"></entry></a></div>
<div id="duration-chart"><svg></svg></div>
{% include 'tracker/entry_table.html' with detailed=True %}
<div class="text-center">{% bootstrap_pagination page_obj %}</div>
{% endblock section_content %}

{% block section_foot %}
<script type="text/javascript">
    $(document).ready(function() {
        durationChart('#duration-chart svg', {{ duration_data|safe }}, function(x) {
            return x === undefined ? '' : d3.time.format('%Y-%m-%d')(new Date(x[0]));
        });
    });
</script>
{% endblock section_foot %}

web/tracker/templates/tracker/entry_table.html
{% load tracker %}
<table class="table table-condensed">
    {% for entry in entry_list %}
    <tr>
        <td class="datetime">{{ entry.datetime }}</td>
        <td>
            <a href="{{ entry.event.get_absolute_url }}">{{ entry.event.title|article }}</a>
            {% if entry.event.description %}
            — {{ entry.event.description }}
            {% endif %}
            {% if entry.annotation %}
            — {{ entry.annotation }}
            {% endif %}
        </td>
        <td class="duration">{{ entry.duration|hours }}</td>
        {% if detailed %}
        <td class="update"><a href="{% url 'tracker:entries:update' entry.pk %}"><entry class="glyphicon glyphicon-edit"></entry></a></td>
        {% endif %}
    </tr>
    {% endfor %}
</table>

web/tracker/templates/tracker/event_detail.html
{% extends 'tracker/base.html' %}
{% load staticfiles %}
{% load tracker %}

{% block section_title %}{{ event.title|article }} - {% endblock %}

{% block section_content %}
<h2>{{ event.title|article }}</h2>
<div class="title-icon">
    <a href="{% url 'tracker:events:update' event.pk %}"><entry class="glyphicon glyphicon-edit"></entry></a>
    <a href="{% url 'tracker:entries:create' %}?event={{ event.pk }}"><entry class="glyphicon glyphicon-plus"></entry></a>
</div>
<div class="row">
    <div class="col-md-4">
        <table class="table table-condensed">
            {% if event.description %}
            <tr>
                <td>Description</td>
                <td>{{ event.description }}</td>
            </tr>
            {% endif %}
            <tr>
                <td>Date</td>
                <td>{{ event.date }}</td>
            </tr>
            <tr>
                <td>Progress</td>
                <td>{{ event.progress|icon }}</td>
            </tr>
            <tr>
                <td>Rating</td>
                <td>{{ event.rating|stars }}</td>
            </tr>
            <tr>
                <td>Time</td>
                <td>{{ event.get_duration|hours }}</td>
            </tr>
            <tr>
                <td>Count</td>
                <td>{{ event.entry_count }}</td>
            </tr>
            <tr>
                <td>Tags</td>
                <td>
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <a href="{{ tag.get_absolute_url }}">{{ tag.value|article }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
        </table>
    </div>
    <div class="col-md-8">
        <div id="duration-chart"><svg></svg></div>
        <h3>Entries</h3>
        {% include 'tracker/entry_table.html' with detailed=True %}
    </div>
</div>
{% endblock section_content %}

{% block section_foot %}
<script type="text/javascript">
    $(document).ready(function() {
        durationChart('#duration-chart svg', {{ duration_data|safe }}, function(x) {
            return x === undefined ? '' : d3.time.format('%Y-%m-%d')(new Date(x[0]));
        });
    });
</script>
{% endblock section_foot %}

web/tracker/templates/tracker/event_form.html
{% extends 'tracker/base.html' %}
{% load bootstrap3 %}
{% load tracker %}

{% block section_title %}Edit - {% endblock %}

{% block section_content %}
<h2>Edit item</h2>
<form method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <div class="form-group text-right">
        <input type="submit" class="btn btn-default" value="Save"/>
    </div>
</form>
{% endblock section_content %}

web/tracker/templates/tracker/event_list.html
{% extends 'tracker/base.html' %}
{% load bootstrap3 %}

{% block section_title %}Events - {% endblock %}

{% block section_content %}
<h2>Events</h2>
<div class="title-icon"><a href="{% url 'tracker:events:create' %}"><entry class="glyphicon glyphicon-plus"></entry></a></div>
{% include 'tracker/event_table.html' with separator='year' %}
<div class="text-center">{% bootstrap_pagination page_obj %}</div>
{% endblock section_content %}

web/tracker/templates/tracker/event_table.html
{% load tracker %}
<table class="table table-condensed">
    {% for event in event_list %}
    {% if separator == 'year' %}
    {% ifchanged %}
    <tr>
        <td colspan="3"><h4>{{ event.date|date:'Y' }}</h4></td>
    </tr>
    {% endifchanged %}
    {% endif %}
    <tr>
        <td><a href="{{ event.get_absolute_url }}">{{ event.title|article }}</a>{% if event.description %} — {{ event.description }}{% endif %}</td>
        <td class="duration">{{ event.duration|hours }}</td>
        <td class="rating">{{ event.rating|stars }}</td>
    </tr>
    {% endfor %}
</table>

web/tracker/templates/tracker/index.html
{% extends 'tracker/base.html' %}

{% block section_content %}
<div class="row">
    <div class="col-md-6">
        <h2>Ongoing</h2>
        {% include 'tracker/event_table.html' with event_list=ongoing_events %}
    </div>
    <div class="col-md-6">
        <h2>Waiting</h2>
        {% include 'tracker/event_table.html' with event_list=waiting_events %}
    </div>
</div>
{% if pending_entries %}
<h2>Open</h2>
{% include 'tracker/entry_table.html' with entry_list=pending_entries detailed=True %}
{% endif %}
{% endblock section_content %}

web/tracker/templates/tracker/stats.html
{% extends 'tracker/base.html' %}

{% block section_content %}
<h2>Yearly</h2>
<div id="yearly-chart"><svg></svg></div>
<h2>Monthly</h2>
<div id="monthly-chart"><svg></svg></div>
<h2>Daily</h2>
<div id="weekday-chart"><svg></svg></div>
<h2>This week in...</h2>
{% for year, entry_list in n_years_ago %}
<h4>{{ year }}</h4>
{% include 'tracker/entry_table.html' %}
{% endfor %}
{% endblock section_content %}

{% block section_foot %}
<script type="text/javascript">
    $(document).ready(function() {
        durationChart('#yearly-chart svg', {{ yearly_data|safe }}, function(x) {
            return x === undefined ? '' : d3.time.format('%Y')(new Date(x[0]));
        });
        durationChart('#monthly-chart svg', {{ monthly_data|safe }}, function(x) {
            return x === undefined ? '' : d3.time.format('%Y-%m')(new Date(x[0]));
        });
        var dayNames = {
            0: 'Mo',
            1: 'Tu',
            2: 'We',
            3: 'Th',
            4: 'Fr',
            5: 'Sa',
            6: 'Su',
        };
        durationChart('#weekday-chart svg', {{ weekday_data|safe }}, function(x) {
            return x === undefined ? '' : dayNames[x[0]];
        });
    });
</script>
{% endblock section_foot %}

web/tracker/templates/tracker/tag_detail.html
{% extends 'tracker/base.html' %}
{% load tracker %}

{% block section_title %}{{ tag.value|article }} - {% endblock %}

{% block section_content %}
<h2><em>{{ tag.value|article }}</em></h2>
<div class="row">
    <div class="col-md-4">
        <table class="table table-condensed">
            <tr>
                <td>Rating</td>
                <td>{{ tag.get_rating|stars }}</td>
            </tr>
            <tr>
                <td>Time</td>
                <td>{{ tag.get_duration|hours }}</td>
            </tr>
            <tr>
                <td>Entry count</td>
                <td>{{ tag.entry_count }}</td>
            </tr>
            <tr>
                <td>Event count</td>
                <td>{{ tag.event_count }}</td>
            </tr>
        </table>
        <h3>Top</h3>
        {% include 'tracker/event_table.html' %}
    </div>
    <div class="col-md-8">
        <div id="duration-chart"><svg></svg></div>
        <h3>Entries</h3>
        {% include 'tracker/entry_table.html' with detailed=True %}
    </div>
</div>
{% endblock section_content %}

{% block section_foot %}
<script type="text/javascript">
    $(document).ready(function() {
        durationChart('#duration-chart svg', {{ duration_data|safe }}, function(x) {
            return x === undefined ? '' : d3.time.format('%Y-%m')(new Date(x[0]));
        });
    });
</script>
{% endblock section_foot %}

web/tracker/templates/tracker/tag_list.html
{% extends 'tracker/base.html' %}
{% load bootstrap3 %}

{% block section_title %}Tags - {% endblock %}

{% block section_content %}
<h2>Tags</h2>
{% include 'tracker/tag_table.html' with separator='initial' %}
<div class="text-center">{% bootstrap_pagination page_obj %}</div>
{% endblock section_content %}

web/tracker/templates/tracker/tag_table.html
{% load tracker %}
<table class="table table-condensed">
    {% for tag in tag_list %}
    {% if separator == 'initial' %}
    {% ifchanged %}
    <tr>
        <td colspan="3"><h4>{{ tag.value.0.upper }}</h4></td>
    </tr>
    {% endifchanged %}
    {% endif %}
    <tr>
        <td><a href="{{ tag.get_absolute_url }}">{{ tag.value|article }}</a></td>
        <td class="duration">{{ tag.duration|hours }}</td>
        <td class="rating">{{ tag.rating|stars }}</td>
    </tr>
    {% endfor %}
</table>

web/tracker/templates/tracker/top.html
{% extends 'tracker/base.html' %}
{% load tracker %}

{% block section_head %}
<style type="text/css" media="screen">
    ul {
        list-style: none;
    }
</style>
{% endblock section_head %}

{% block section_content %}
<table>
    {% for event in event_list %}
    <tr>
        <td>{{ event.title|article }}{% if event.description %} — {{ event.description }}{% endif %}</td>
        <td>{{ event.rating|stars }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock section_content %}